# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5b630bf9112e6d2f8b4d02b24d8151a0af07f73ab513a50ba30c234ea940c7ff01cf15c7e7f4f39255dda7628931f300e8b47c68f866a30c95e44cc3fb58417

test:
  secret_key_base: b05114456ff4e7919a51e735ea6cb1a2dfd9797acc391696c45508eedd9711765da16c7d27822b9b0154c1aead3b6b1790469b5b2a749d0100630f3ccaa51ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
